name: deploy-main

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '12.14.0'
  NETLIFY_APP_ID: '348f54ab-fd22-43ef-b919-00a8d00e4fa3'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_TODO }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci --no-optional
        npm i -g netlify-cli
      if: success()
    - name: Build
      run: npm run build
      if: success()
    - name: Deploy
      run: npm run deploy
      if: success()
